import { addDays, format, startOfMonth, subDays, subMonths } from "date-fns";

import type {
  Account,
  Budget,
  Category,
  Goal,
  RecurringItem,
  Transaction,
} from "@/lib/saku-types";

const today = new Date();
const currentMonthStart = startOfMonth(today);
const previousMonthStart = startOfMonth(subMonths(today, 1));
const twoMonthsAgoStart = startOfMonth(subMonths(today, 2));

const toDate = (value: Date) => format(value, "yyyy-MM-dd");

export const demoAccounts: Account[] = [
  {
    id: "acct-wallet",
    name: "Dompet Harian",
    type: "dompet",
    currency: "IDR",
    institution: null,
  },
  {
    id: "acct-bank",
    name: "Bank Kampus",
    type: "bank",
    currency: "IDR",
    institution: "BCA",
  },
  {
    id: "acct-ewallet",
    name: "GoPay",
    type: "ewallet",
    currency: "IDR",
    institution: "Gojek",
  },
  {
    id: "acct-saving",
    name: "Tabungan Laptop",
    type: "tabungan",
    currency: "IDR",
    institution: "Jago",
  },
];

export const demoCategories: Category[] = [
  { id: "cat-income", name: "Uang Saku", color: "#157f5b" },
  { id: "cat-freelance", name: "Freelance", color: "#1d7874" },
  { id: "cat-kos", name: "Kos", color: "#8c5e34" },
  { id: "cat-food", name: "Makan", color: "#f59e0b" },
  { id: "cat-hangout", name: "Nongkrong", color: "#e76f51" },
  { id: "cat-transport", name: "Transport", color: "#3b82f6" },
  { id: "cat-academic", name: "Akademik", color: "#6366f1" },
  { id: "cat-saving", name: "Tabungan", color: "#16a34a" },
];

export const demoTransactions: Transaction[] = [
  {
    id: "tx-001",
    accountId: "acct-bank",
    amount: 2500000,
    currency: "IDR",
    type: "credit",
    categoryId: "cat-income",
    merchant: "Transfer Orang Tua",
    description: "Uang saku bulanan",
    date: toDate(addDays(currentMonthStart, 1)),
    status: "cleared",
    imported: false,
    tags: ["bulanan"],
  },
  {
    id: "tx-002",
    accountId: "acct-bank",
    amount: 750000,
    currency: "IDR",
    type: "credit",
    categoryId: "cat-freelance",
    merchant: "Project Landing Page",
    description: "Bayaran freelance",
    date: toDate(addDays(currentMonthStart, 4)),
    status: "cleared",
    imported: false,
    tags: ["side-hustle"],
  },
  {
    id: "tx-003",
    accountId: "acct-bank",
    amount: 950000,
    currency: "IDR",
    type: "debit",
    categoryId: "cat-kos",
    merchant: "Kos Putra Melati",
    description: "Bayar kos bulan ini",
    date: toDate(addDays(currentMonthStart, 2)),
    status: "cleared",
    imported: false,
    tags: ["rutin"],
  },
  {
    id: "tx-004",
    accountId: "acct-ewallet",
    amount: 42000,
    currency: "IDR",
    type: "debit",
    categoryId: "cat-food",
    merchant: "Warmindo 24 Jam",
    description: "Makan malam",
    date: toDate(subDays(today, 2)),
    status: "cleared",
    imported: false,
    tags: ["makan"],
  },
  {
    id: "tx-005",
    accountId: "acct-ewallet",
    amount: 85000,
    currency: "IDR",
    type: "debit",
    categoryId: "cat-hangout",
    merchant: "Kopi Sore",
    description: "Ngopi bareng kelompok",
    date: toDate(subDays(today, 4)),
    status: "cleared",
    imported: false,
    tags: ["nongkrong"],
  },
  {
    id: "tx-006",
    accountId: "acct-ewallet",
    amount: 27000,
    currency: "IDR",
    type: "debit",
    categoryId: "cat-transport",
    merchant: "Gojek",
    description: "Pulang kampus",
    date: toDate(subDays(today, 1)),
    status: "cleared",
    imported: false,
    tags: ["transport"],
  },
  {
    id: "tx-007",
    accountId: "acct-bank",
    amount: 180000,
    currency: "IDR",
    type: "debit",
    categoryId: "cat-academic",
    merchant: "Gramedia",
    description: "Beli buku statistika",
    date: toDate(addDays(currentMonthStart, 8)),
    status: "cleared",
    imported: false,
    tags: ["kuliah"],
  },
  {
    id: "tx-008",
    accountId: "acct-saving",
    amount: 300000,
    currency: "IDR",
    type: "debit",
    categoryId: "cat-saving",
    merchant: "Auto Save",
    description: "Top up tabungan laptop",
    date: toDate(addDays(currentMonthStart, 10)),
    status: "cleared",
    imported: false,
    tags: ["goal"],
  },
  {
    id: "tx-009",
    accountId: "acct-bank",
    amount: 2500000,
    currency: "IDR",
    type: "credit",
    categoryId: "cat-income",
    merchant: "Transfer Orang Tua",
    description: "Uang saku Februari",
    date: toDate(addDays(previousMonthStart, 1)),
    status: "cleared",
    imported: false,
    tags: ["bulanan"],
  },
  {
    id: "tx-010",
    accountId: "acct-bank",
    amount: 950000,
    currency: "IDR",
    type: "debit",
    categoryId: "cat-kos",
    merchant: "Kos Putra Melati",
    description: "Bayar kos Februari",
    date: toDate(addDays(previousMonthStart, 3)),
    status: "cleared",
    imported: false,
    tags: ["rutin"],
  },
  {
    id: "tx-011",
    accountId: "acct-ewallet",
    amount: 395000,
    currency: "IDR",
    type: "debit",
    categoryId: "cat-food",
    merchant: "Beragam Merchant",
    description: "Akumulasi makan minggu UTS",
    date: toDate(addDays(previousMonthStart, 11)),
    status: "cleared",
    imported: false,
    tags: ["makan"],
  },
  {
    id: "tx-012",
    accountId: "acct-ewallet",
    amount: 220000,
    currency: "IDR",
    type: "debit",
    categoryId: "cat-hangout",
    merchant: "Cafe Lobi",
    description: "Diskusi organisasi",
    date: toDate(addDays(previousMonthStart, 14)),
    status: "cleared",
    imported: false,
    tags: ["nongkrong"],
  },
  {
    id: "tx-013",
    accountId: "acct-bank",
    amount: 2500000,
    currency: "IDR",
    type: "credit",
    categoryId: "cat-income",
    merchant: "Transfer Orang Tua",
    description: "Uang saku Januari",
    date: toDate(addDays(twoMonthsAgoStart, 2)),
    status: "cleared",
    imported: false,
    tags: ["bulanan"],
  },
  {
    id: "tx-014",
    accountId: "acct-ewallet",
    amount: 145000,
    currency: "IDR",
    type: "debit",
    categoryId: "cat-transport",
    merchant: "Gojek dan KRL",
    description: "Mobilitas awal semester",
    date: toDate(addDays(twoMonthsAgoStart, 8)),
    status: "cleared",
    imported: false,
    tags: ["transport"],
  },
  {
    id: "tx-015",
    accountId: "acct-ewallet",
    amount: 320000,
    currency: "IDR",
    type: "debit",
    categoryId: "cat-food",
    merchant: "Meal Prep",
    description: "Belanja stok seminggu",
    date: toDate(addDays(twoMonthsAgoStart, 13)),
    status: "cleared",
    imported: false,
    tags: ["makan"],
  },
];

export const demoBudgets: Omit<
  Budget,
  "categoryName" | "categoryColor" | "spentAmount" | "progress" | "status"
>[] = [
  {
    id: "budget-food",
    categoryId: "cat-food",
    period: "bulanan",
    limitAmount: 900000,
    startDate: toDate(currentMonthStart),
    endDate: toDate(addDays(currentMonthStart, 30)),
  },
  {
    id: "budget-hangout",
    categoryId: "cat-hangout",
    period: "bulanan",
    limitAmount: 350000,
    startDate: toDate(currentMonthStart),
    endDate: toDate(addDays(currentMonthStart, 30)),
  },
  {
    id: "budget-transport",
    categoryId: "cat-transport",
    period: "bulanan",
    limitAmount: 300000,
    startDate: toDate(currentMonthStart),
    endDate: toDate(addDays(currentMonthStart, 30)),
  },
  {
    id: "budget-academic",
    categoryId: "cat-academic",
    period: "bulanan",
    limitAmount: 400000,
    startDate: toDate(currentMonthStart),
    endDate: toDate(addDays(currentMonthStart, 30)),
  },
];

export const demoGoals: Goal[] = [
  {
    id: "goal-laptop",
    name: "Beli laptop baru",
    targetAmount: 5000000,
    currentAmount: 1850000,
    progress: 0.37,
    targetDate: toDate(addDays(today, 120)),
    note: "Fokus tambah tabungan dari freelance dan potong budget nongkrong.",
  },
  {
    id: "goal-emergency",
    name: "Dana darurat semester depan",
    targetAmount: 2000000,
    currentAmount: 650000,
    progress: 0.325,
    targetDate: toDate(addDays(today, 180)),
    note: "Simpan minimal Rp150.000 tiap awal bulan.",
  },
];

export const demoRecurringItems: RecurringItem[] = [
  {
    id: "recurring-kos",
    label: "Bayar kos",
    amount: 950000,
    categoryName: "Kos",
    nextOccurrence: toDate(addDays(currentMonthStart, 32)),
  },
  {
    id: "recurring-spotify",
    label: "Spotify Student",
    amount: 32990,
    categoryName: "Nongkrong",
    nextOccurrence: toDate(addDays(today, 9)),
  },
  {
    id: "recurring-wifi",
    label: "Wi-Fi Patungan",
    amount: 75000,
    categoryName: "Kos",
    nextOccurrence: toDate(addDays(today, 5)),
  },
];
